name: {{plugin_name.snakeCase()}}_android

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - ".github/workflows/{{plugin_name.snakeCase()}}_android.yaml"
      - "{{plugin_name.snakeCase()}}_android/**"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/{{plugin_name.snakeCase()}}_android.yaml"
      - "{{plugin_name.snakeCase()}}_android/**"

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      flutter_channel: stable
      flutter_version: 3.3.2
      working_directory: {{plugin_name.snakeCase()}}_android

